name: PR test before merging
on:
  pull_request:
    branches: [dev, main]

jobs:
  CI-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Check lint
        run: yarn eslint src/**/*.(tsx|ts|js|jsx)

      - name: Check format
        run: yarn prettier src/**/*.(tsx|ts|js|jsx) --check
        
      - name: Check types
        run: tsc -p tsconfig.json --noEmit
  
  Build-Test:
    runs-on: ubuntu-latest
    needs: [CI-Test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build project
        run: yarn build
